languageCode = "en-us"
DefaultContentLanguage = "en"
title = "Cocoon Rwanda"
baseURL = "https://cocoonrwanda.101experiments.com/"
theme = "dopetrope"

[params.houze]
    title = "Houses"
    viewalltext = "All Houses"
    foldername = "houses"

[params.appartzment]
    title = "Apartments"
    viewalltext = "All Apartments"
    foldername = "apartments"

[params.settings]
    googleanalytics = "UA-119431851-1"
