languageCode = "en-us"
title = "Cocoon Rwanda"
baseURL = "https://cocoonrwanda.101experiments.com/"
theme = "dopetrope"

[params.blog]
    title = "Rentals"
    viewalltext = "All Rentals"
    foldername = "properties"

[params.settings]
    googleanalytics = "UA-119431851-1"
