languageCode = "en-us"
DefaultContentLanguage = "en"
title = "Cocoon Rwanda"
baseURL = "https://cocoonrwanda.101experiments.com/"
theme = "dopetrope"

[params.houze]
    title = "Houses"
    viewalltext = "All Houses"
    foldername = "houses"

[params.appartzment]
    title = "Appartments"
    viewalltext = "All Appartments"
    foldername = "appartments"

[params.shortzterm]
    title = "Short Terms"
    viewalltext = "All Short Terms"
    foldername = "shortterms"

[params.settings]
    googleanalytics = "UA-119431851-1"
