languageCode = "en-us"
title = "Cocoon Rwanda"
baseURL = "https://cocoonrwanda.101experiments.com/"
theme = "dopetrope"

[params.portfolio]
    title = "Appartments"
    foldername = "appartments"
    findoutmoretext = "View Detailed Appartment"

[params.blog]
    title = "Properties"
    viewalltext = "All Properties"
    foldername = "properties"

[params.settings]
    googleanalytics = "UA-119431851-1"
