languageCode = "en-us"
DefaultContentLanguage = "en"
title = "Cocoon Rwanda"
baseURL = "https://cocoonrwanda.101experiments.com"
theme = "dopetrope"

[params.houze]
    title = "Houses"
    viewalltext = "All Houses"
    foldername = "houses"

[params.appartzment]
    title = "Appartments"
    viewalltext = "All Appartments"
    foldername = "appartments"

#[params.shortzstay]
#    title = "Short Stay"
#    viewalltext = "All Short Stays"
#    foldername = "shortstays"

[params.settings]
    googleanalytics = "UA-119431851-1"
