languageCode = "en-us"
title = "Cocoon Rwanda"
baseURL = "https://laughing-ardinghelli-0e859f.netlify.com/"
theme = "dopetrope"

[params.portfolio]
    title = "Appartments"
    foldername = "appartments"
    findoutmoretext = "View Detailed Appartment"

[params.blog]
    title = "Houses"
    viewalltext = "All Houses"
    foldername = "houses"

[params.settings]
    googleanalytics = "UA-119431851-1"
