backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
  accept_roles: #optional - accepts all users if left out
    - admin
    - editor

publish_mode: editorial_workflow

media_folder: "static/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads

display_url: https://cocoonrwanda.101experiments.com

collections:

  - name: "properties" # Used in routes, e.g., /admin/collections/posts
    label: "Properties" # Used in the UI
    label_singular: "Property"
    folder: "content/properties" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Property Type", name: "property", required: true, widget: "select", options: ["House", "Appartment", "Short Term"]}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", required: false, widget: "datetime"}
      - {label: "Draft", name: "draft", required: false, widget: "hidden", default: false}
      - {label: "Hide sidebar", name: "hidesidebar", required: false, widget: "hidden", default: true}
      - {label: "Short Description", name: "description", required: true, widget: "string"}
      - {label: "Thumbnail Image", name: "thumbnail", required: false, widget: "image"}
      - {label: "Image", name: "image", required: false, widget: "image"}
      - {label: "N° of Bedrooms", name: "bedrooms", required: true, widget: "select", options: ["0", "1", "2", "3", "4", "5", "6+"]}
      - {label: "N° of Bathsrooms", name: "baths", required: true, widget: "select", options: ["0", "1", "2", "3", "4+"]}
      - {label: "Furnished", name: "furnished", required: true, widget: "select", options: ["Yes", "No"]}
      - {label: "N° of Floors", name: "floors", required: true, widget: "select", options: ["Ground Floor", "1", "2", "3", "4+"]}
      - {label: "N° of Sleeps", name: "sleeps", required: true, widget: "select", options: ["0", "1", "2", "3", "4", "5", "6+"]}
      - {label: "Garden", name: "garden", required: true, widget: "select", options: ["Yes", "No"]}
      - {label: "Maid Service", name: "maid", required: true, widget: "select", options: ["Yes", "No"]}
      - {label: "TV", name: "tv", required: true, widget: "select", options: ["Yes", "No"]}
      - {label: "Wifi", name: "wifi", required: true, widget: "select", options: ["Yes", "No"]}
      - {label: "Hot Water", name: "hotwater", required: true, widget: "select", options: ["Yes", "No"]}
      - {label: "Water Pump", name: "waterpump", required: true, widget: "select", options: ["Yes", "No"]}
      - {label: "Pets Allowed", name: "pets", required: true, widget: "select", options: ["Yes", "No"]}
      - {label: "N° of Parking spots", name: "parking", required: true, widget: "select", options: ["0", "1", "2", "3", "4", "5", "6+"]}
      - {label: "Security", name: "security", required: true, widget: "select", options: ["Yes", "No"]}
      - {label: "Price", name: "price", required: true, widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
